spring:
  jpa:
    properties:
      hibernate:
        #        default_batch_fetch_size: 100
        #        auto_quote_keyword: true
        format_sql: true
        jdbc:
          batch_size: 1000

    hibernate:
      ddl-auto: update
    show-sql: true


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1?characterEncoding=UTF-8&serverTimezone=UTC
    username: user
    password: user

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  server:
    port: 18088
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      hibernate:
        type: trace